#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: tekton-source-pipelinerun
spec:
  outputs:
    url: spec.params[?(@.name=="source-url")].value
    revision: spec.params[?(@.name=="source-revision")].value

  template:
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
    spec:
      workspaces:
        - name: custom-maven-settings
          secret:
            secretName: maven-settings
        - name: maven-settings
          subPath: maven-repo-cache
          persistentVolumeClaim:
            claimName: supplychainpvc
        - name: supplychain-workspace
          emptyDir: {}
      pipelineRef:
        name: $(selected.metadata.name)$
      params: $(runnable.spec.inputs.tekton-params)$
