#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-ssh-secret
data:
  identity: #@ data.values.git_writer.base64_encoded_ssh_key
  known_hosts: #@ data.values.git_writer.base64_encoded_known_hosts