#@ load("@ytt:data", "data")

#@ if/end "tekton-taskrun" not in data.values.excluded_templates:
---
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: tekton-taskrun
spec:
  outputs:
    url: spec.params[?(@.name=="git_repository")].value
    revision: spec.params[?(@.name=="git_branch")].value
  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: $(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
    spec:
      serviceAccountName: $(runnable.spec.inputs.serviceAccount)$
      taskRef: $(runnable.spec.inputs.taskRef)$
      params: $(runnable.spec.inputs.params)$
